/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageMetricsRouteImport } from './routes/usage-metrics'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppealsRouteImport } from './routes/appeals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ContentsIndexRouteImport } from './routes/contents.index'
import { Route as UsersUserIdRouteImport } from './routes/users.$userId'
import { Route as ReportsReportIdRouteImport } from './routes/reports.$reportId'
import { Route as ContentsContentIdRouteImport } from './routes/contents.$contentId'

const UsageMetricsRoute = UsageMetricsRouteImport.update({
  id: '/usage-metrics',
  path: '/usage-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealsRoute = AppealsRouteImport.update({
  id: '/appeals',
  path: '/appeals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentsIndexRoute = ContentsIndexRouteImport.update({
  id: '/contents/',
  path: '/contents/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdRoute = UsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsReportIdRoute = ReportsReportIdRouteImport.update({
  id: '/reports/$reportId',
  path: '/reports/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentsContentIdRoute = ContentsContentIdRouteImport.update({
  id: '/contents/$contentId',
  path: '/contents/$contentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appeals': typeof AppealsRoute
  '/login': typeof LoginRoute
  '/usage-metrics': typeof UsageMetricsRoute
  '/contents/$contentId': typeof ContentsContentIdRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/contents/': typeof ContentsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appeals': typeof AppealsRoute
  '/login': typeof LoginRoute
  '/usage-metrics': typeof UsageMetricsRoute
  '/contents/$contentId': typeof ContentsContentIdRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/contents': typeof ContentsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/users': typeof UsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appeals': typeof AppealsRoute
  '/login': typeof LoginRoute
  '/usage-metrics': typeof UsageMetricsRoute
  '/contents/$contentId': typeof ContentsContentIdRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/users/$userId': typeof UsersUserIdRoute
  '/contents/': typeof ContentsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/users/': typeof UsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appeals'
    | '/login'
    | '/usage-metrics'
    | '/contents/$contentId'
    | '/reports/$reportId'
    | '/users/$userId'
    | '/contents/'
    | '/reports/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appeals'
    | '/login'
    | '/usage-metrics'
    | '/contents/$contentId'
    | '/reports/$reportId'
    | '/users/$userId'
    | '/contents'
    | '/reports'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/appeals'
    | '/login'
    | '/usage-metrics'
    | '/contents/$contentId'
    | '/reports/$reportId'
    | '/users/$userId'
    | '/contents/'
    | '/reports/'
    | '/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppealsRoute: typeof AppealsRoute
  LoginRoute: typeof LoginRoute
  UsageMetricsRoute: typeof UsageMetricsRoute
  ContentsContentIdRoute: typeof ContentsContentIdRoute
  ReportsReportIdRoute: typeof ReportsReportIdRoute
  UsersUserIdRoute: typeof UsersUserIdRoute
  ContentsIndexRoute: typeof ContentsIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage-metrics': {
      id: '/usage-metrics'
      path: '/usage-metrics'
      fullPath: '/usage-metrics'
      preLoaderRoute: typeof UsageMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeals': {
      id: '/appeals'
      path: '/appeals'
      fullPath: '/appeals'
      preLoaderRoute: typeof AppealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contents/': {
      id: '/contents/'
      path: '/contents'
      fullPath: '/contents/'
      preLoaderRoute: typeof ContentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId': {
      id: '/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof UsersUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$reportId': {
      id: '/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof ReportsReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contents/$contentId': {
      id: '/contents/$contentId'
      path: '/contents/$contentId'
      fullPath: '/contents/$contentId'
      preLoaderRoute: typeof ContentsContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppealsRoute: AppealsRoute,
  LoginRoute: LoginRoute,
  UsageMetricsRoute: UsageMetricsRoute,
  ContentsContentIdRoute: ContentsContentIdRoute,
  ReportsReportIdRoute: ReportsReportIdRoute,
  UsersUserIdRoute: UsersUserIdRoute,
  ContentsIndexRoute: ContentsIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
