/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsageMetricsRouteImport } from './routes/usage-metrics'
import { Route as PromptSetsRouteImport } from './routes/prompt-sets'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as AppealsRouteImport } from './routes/appeals'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsersIndexRouteImport } from './routes/users.index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as NoticesIndexRouteImport } from './routes/notices.index'
import { Route as InquiriesIndexRouteImport } from './routes/inquiries.index'
import { Route as ContentsIndexRouteImport } from './routes/contents.index'
import { Route as ReportsReportIdRouteImport } from './routes/reports.$reportId'
import { Route as NoticesNoticeIdRouteImport } from './routes/notices.$noticeId'
import { Route as InquiriesInquiryIdRouteImport } from './routes/inquiries.$inquiryId'
import { Route as ContentsContentIdRouteImport } from './routes/contents.$contentId'
import { Route as UsersUserIdIndexRouteImport } from './routes/users.$userId.index'
import { Route as UsersUserIdChatsRoomIdRouteImport } from './routes/users.$userId.chats.$roomId'

const UsageMetricsRoute = UsageMetricsRouteImport.update({
  id: '/usage-metrics',
  path: '/usage-metrics',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptSetsRoute = PromptSetsRouteImport.update({
  id: '/prompt-sets',
  path: '/prompt-sets',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const AppealsRoute = AppealsRouteImport.update({
  id: '/appeals',
  path: '/appeals',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersIndexRoute = UsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesIndexRoute = NoticesIndexRouteImport.update({
  id: '/notices/',
  path: '/notices/',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiriesIndexRoute = InquiriesIndexRouteImport.update({
  id: '/inquiries/',
  path: '/inquiries/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentsIndexRoute = ContentsIndexRouteImport.update({
  id: '/contents/',
  path: '/contents/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsReportIdRoute = ReportsReportIdRouteImport.update({
  id: '/reports/$reportId',
  path: '/reports/$reportId',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesNoticeIdRoute = NoticesNoticeIdRouteImport.update({
  id: '/notices/$noticeId',
  path: '/notices/$noticeId',
  getParentRoute: () => rootRouteImport,
} as any)
const InquiriesInquiryIdRoute = InquiriesInquiryIdRouteImport.update({
  id: '/inquiries/$inquiryId',
  path: '/inquiries/$inquiryId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContentsContentIdRoute = ContentsContentIdRouteImport.update({
  id: '/contents/$contentId',
  path: '/contents/$contentId',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdIndexRoute = UsersUserIdIndexRouteImport.update({
  id: '/users/$userId/',
  path: '/users/$userId/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersUserIdChatsRoomIdRoute = UsersUserIdChatsRoomIdRouteImport.update({
  id: '/users/$userId/chats/$roomId',
  path: '/users/$userId/chats/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appeals': typeof AppealsRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/prompt-sets': typeof PromptSetsRoute
  '/usage-metrics': typeof UsageMetricsRoute
  '/contents/$contentId': typeof ContentsContentIdRoute
  '/inquiries/$inquiryId': typeof InquiriesInquiryIdRoute
  '/notices/$noticeId': typeof NoticesNoticeIdRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/contents/': typeof ContentsIndexRoute
  '/inquiries/': typeof InquiriesIndexRoute
  '/notices/': typeof NoticesIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/users/$userId/': typeof UsersUserIdIndexRoute
  '/users/$userId/chats/$roomId': typeof UsersUserIdChatsRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appeals': typeof AppealsRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/prompt-sets': typeof PromptSetsRoute
  '/usage-metrics': typeof UsageMetricsRoute
  '/contents/$contentId': typeof ContentsContentIdRoute
  '/inquiries/$inquiryId': typeof InquiriesInquiryIdRoute
  '/notices/$noticeId': typeof NoticesNoticeIdRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/contents': typeof ContentsIndexRoute
  '/inquiries': typeof InquiriesIndexRoute
  '/notices': typeof NoticesIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/users': typeof UsersIndexRoute
  '/users/$userId': typeof UsersUserIdIndexRoute
  '/users/$userId/chats/$roomId': typeof UsersUserIdChatsRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appeals': typeof AppealsRoute
  '/legal': typeof LegalRoute
  '/login': typeof LoginRoute
  '/prompt-sets': typeof PromptSetsRoute
  '/usage-metrics': typeof UsageMetricsRoute
  '/contents/$contentId': typeof ContentsContentIdRoute
  '/inquiries/$inquiryId': typeof InquiriesInquiryIdRoute
  '/notices/$noticeId': typeof NoticesNoticeIdRoute
  '/reports/$reportId': typeof ReportsReportIdRoute
  '/contents/': typeof ContentsIndexRoute
  '/inquiries/': typeof InquiriesIndexRoute
  '/notices/': typeof NoticesIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/users/': typeof UsersIndexRoute
  '/users/$userId/': typeof UsersUserIdIndexRoute
  '/users/$userId/chats/$roomId': typeof UsersUserIdChatsRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appeals'
    | '/legal'
    | '/login'
    | '/prompt-sets'
    | '/usage-metrics'
    | '/contents/$contentId'
    | '/inquiries/$inquiryId'
    | '/notices/$noticeId'
    | '/reports/$reportId'
    | '/contents/'
    | '/inquiries/'
    | '/notices/'
    | '/reports/'
    | '/users/'
    | '/users/$userId/'
    | '/users/$userId/chats/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appeals'
    | '/legal'
    | '/login'
    | '/prompt-sets'
    | '/usage-metrics'
    | '/contents/$contentId'
    | '/inquiries/$inquiryId'
    | '/notices/$noticeId'
    | '/reports/$reportId'
    | '/contents'
    | '/inquiries'
    | '/notices'
    | '/reports'
    | '/users'
    | '/users/$userId'
    | '/users/$userId/chats/$roomId'
  id:
    | '__root__'
    | '/'
    | '/appeals'
    | '/legal'
    | '/login'
    | '/prompt-sets'
    | '/usage-metrics'
    | '/contents/$contentId'
    | '/inquiries/$inquiryId'
    | '/notices/$noticeId'
    | '/reports/$reportId'
    | '/contents/'
    | '/inquiries/'
    | '/notices/'
    | '/reports/'
    | '/users/'
    | '/users/$userId/'
    | '/users/$userId/chats/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppealsRoute: typeof AppealsRoute
  LegalRoute: typeof LegalRoute
  LoginRoute: typeof LoginRoute
  PromptSetsRoute: typeof PromptSetsRoute
  UsageMetricsRoute: typeof UsageMetricsRoute
  ContentsContentIdRoute: typeof ContentsContentIdRoute
  InquiriesInquiryIdRoute: typeof InquiriesInquiryIdRoute
  NoticesNoticeIdRoute: typeof NoticesNoticeIdRoute
  ReportsReportIdRoute: typeof ReportsReportIdRoute
  ContentsIndexRoute: typeof ContentsIndexRoute
  InquiriesIndexRoute: typeof InquiriesIndexRoute
  NoticesIndexRoute: typeof NoticesIndexRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
  UsersIndexRoute: typeof UsersIndexRoute
  UsersUserIdIndexRoute: typeof UsersUserIdIndexRoute
  UsersUserIdChatsRoomIdRoute: typeof UsersUserIdChatsRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usage-metrics': {
      id: '/usage-metrics'
      path: '/usage-metrics'
      fullPath: '/usage-metrics'
      preLoaderRoute: typeof UsageMetricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompt-sets': {
      id: '/prompt-sets'
      path: '/prompt-sets'
      fullPath: '/prompt-sets'
      preLoaderRoute: typeof PromptSetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appeals': {
      id: '/appeals'
      path: '/appeals'
      fullPath: '/appeals'
      preLoaderRoute: typeof AppealsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/': {
      id: '/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof UsersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/': {
      id: '/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices/': {
      id: '/notices/'
      path: '/notices'
      fullPath: '/notices/'
      preLoaderRoute: typeof NoticesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiries/': {
      id: '/inquiries/'
      path: '/inquiries'
      fullPath: '/inquiries/'
      preLoaderRoute: typeof InquiriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contents/': {
      id: '/contents/'
      path: '/contents'
      fullPath: '/contents/'
      preLoaderRoute: typeof ContentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/$reportId': {
      id: '/reports/$reportId'
      path: '/reports/$reportId'
      fullPath: '/reports/$reportId'
      preLoaderRoute: typeof ReportsReportIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices/$noticeId': {
      id: '/notices/$noticeId'
      path: '/notices/$noticeId'
      fullPath: '/notices/$noticeId'
      preLoaderRoute: typeof NoticesNoticeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inquiries/$inquiryId': {
      id: '/inquiries/$inquiryId'
      path: '/inquiries/$inquiryId'
      fullPath: '/inquiries/$inquiryId'
      preLoaderRoute: typeof InquiriesInquiryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contents/$contentId': {
      id: '/contents/$contentId'
      path: '/contents/$contentId'
      fullPath: '/contents/$contentId'
      preLoaderRoute: typeof ContentsContentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId/': {
      id: '/users/$userId/'
      path: '/users/$userId'
      fullPath: '/users/$userId/'
      preLoaderRoute: typeof UsersUserIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/users/$userId/chats/$roomId': {
      id: '/users/$userId/chats/$roomId'
      path: '/users/$userId/chats/$roomId'
      fullPath: '/users/$userId/chats/$roomId'
      preLoaderRoute: typeof UsersUserIdChatsRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppealsRoute: AppealsRoute,
  LegalRoute: LegalRoute,
  LoginRoute: LoginRoute,
  PromptSetsRoute: PromptSetsRoute,
  UsageMetricsRoute: UsageMetricsRoute,
  ContentsContentIdRoute: ContentsContentIdRoute,
  InquiriesInquiryIdRoute: InquiriesInquiryIdRoute,
  NoticesNoticeIdRoute: NoticesNoticeIdRoute,
  ReportsReportIdRoute: ReportsReportIdRoute,
  ContentsIndexRoute: ContentsIndexRoute,
  InquiriesIndexRoute: InquiriesIndexRoute,
  NoticesIndexRoute: NoticesIndexRoute,
  ReportsIndexRoute: ReportsIndexRoute,
  UsersIndexRoute: UsersIndexRoute,
  UsersUserIdIndexRoute: UsersUserIdIndexRoute,
  UsersUserIdChatsRoomIdRoute: UsersUserIdChatsRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
