"""Import every model module so `Base.metadata` is fully populated for Alembic autogenerate."""

from api.db.models.auth import AdminUser, GuardianConsent, User, WithdrawnEmail
from api.db.models.character import CharacterVersionDetail, SituationalImage
from api.db.models.chat import (
    CharacterImageExposure,
    ChatMessage,
    ChatMessageReport,
    ChatMessageRole,
    ChatRoom,
    ChatRoomMemorySnapshot,
    ChatRoomStat,
    DiscardedResponse,
    StoryEndingUnlock,
    StoryMediaExposure,
)
from api.db.models.clover import CloverLedger, CloverLot
from api.db.models.comments import (
    Comment,
    CommentLike,
    CommentMention,
    CommentModerationAction,
    CommentMute,
    CommentNotificationPreference,
    CommentReport,
    CommentSticker,
)
from api.db.models.content import (
    Content,
    ContentChatParticipant,
    ContentTarget,
    ContentType,
    ContentVersion,
    ContentVisibility,
    Favorite,
    Genre,
    HomeCuration,
    Like,
    ModerationStatus,
)
from api.db.models.feature_grant import FeatureName, UserFeatureGrant
from api.db.models.inquiry import Inquiry, InquiryCategory, InquiryStatus
from api.db.models.legal import LegalDocument
from api.db.models.media import Asset, AssetKind, AssetStatus, ImageGenerationRequest
from api.db.models.moderation import (
    AdminActionLog,
    Appeal,
    AppealStatus,
    AppealTargetKind,
    AppealVerdict,
    ModerationAction,
    ModerationActionType,
    Notification,
    Report,
    ReportReasonCategory,
    ReportStatus,
)
from api.db.models.notice import Notice
from api.db.models.novel import (
    Novel,
    NovelBatch,
    NovelChapter,
    NovelChapterCharacter,
    NovelChapterRevision,
    NovelCharacter,
    NovelContentType,
    NovelJob,
    NovelJobFailureCode,
    NovelJobKind,
    NovelJobStatus,
    NovelReadingPosition,
    NovelRevisionSource,
    NovelSnapshot,
    NovelSnapshotKind,
)
from api.db.models.persona import UserPersona
from api.db.models.prompt import PromptSection, PromptSet, PublishFilterTextSectionBackup
from api.db.models.story import (
    Ending,
    EndingRule,
    EndingRuleGroup,
    EndingRuleOperator,
    KeywordNote,
    LogicalOp,
    MediaBookCell,
    MediaBookPerson,
    MediaBookScene,
    Shortcut,
    SituationNote,
    StartingSetup,
    StatDef,
    StoryPromptTemplate,
    StoryVersionDetail,
)

__all__ = [
    "AdminActionLog",
    "AdminUser",
    "Appeal",
    "AppealStatus",
    "AppealTargetKind",
    "AppealVerdict",
    "Asset",
    "AssetKind",
    "AssetStatus",
    "CharacterImageExposure",
    "CharacterVersionDetail",
    "ChatMessage",
    "ChatMessageReport",
    "ChatMessageRole",
    "ChatRoom",
    "ChatRoomMemorySnapshot",
    "ChatRoomStat",
    "CloverLedger",
    "CloverLot",
    "Comment",
    "CommentLike",
    "CommentMention",
    "CommentModerationAction",
    "CommentMute",
    "CommentNotificationPreference",
    "CommentReport",
    "CommentSticker",
    "Content",
    "ContentChatParticipant",
    "ContentTarget",
    "ContentType",
    "ContentVersion",
    "ContentVisibility",
    "DiscardedResponse",
    "Ending",
    "EndingRule",
    "EndingRuleGroup",
    "EndingRuleOperator",
    "Favorite",
    "FeatureName",
    "Genre",
    "GuardianConsent",
    "HomeCuration",
    "ImageGenerationRequest",
    "Inquiry",
    "InquiryCategory",
    "InquiryStatus",
    "KeywordNote",
    "LegalDocument",
    "Like",
    "LogicalOp",
    "MediaBookCell",
    "MediaBookPerson",
    "MediaBookScene",
    "ModerationAction",
    "ModerationActionType",
    "ModerationStatus",
    "Notice",
    "Notification",
    "Novel",
    "NovelBatch",
    "NovelChapter",
    "NovelChapterCharacter",
    "NovelChapterRevision",
    "NovelCharacter",
    "NovelContentType",
    "NovelJob",
    "NovelJobFailureCode",
    "NovelJobKind",
    "NovelJobStatus",
    "NovelReadingPosition",
    "NovelRevisionSource",
    "NovelSnapshot",
    "NovelSnapshotKind",
    "PromptSection",
    "PromptSet",
    "PublishFilterTextSectionBackup",
    "Report",
    "ReportReasonCategory",
    "ReportStatus",
    "Shortcut",
    "SituationNote",
    "SituationalImage",
    "StartingSetup",
    "StatDef",
    "StoryEndingUnlock",
    "StoryMediaExposure",
    "StoryPromptTemplate",
    "StoryVersionDetail",
    "User",
    "UserFeatureGrant",
    "UserPersona",
    "WithdrawnEmail",
]
