"""Import every model module so `Base.metadata` is fully populated for Alembic autogenerate."""

from api.db.models.auth import AdminUser, GuardianConsent, User
from api.db.models.character import CharacterVersionDetail, SituationalImage
from api.db.models.chat import (
    CharacterImageExposure,
    ChatMessage,
    ChatMessageRole,
    ChatRoom,
    ChatRoomStat,
    StoryEndingUnlock,
)
from api.db.models.content import (
    Content,
    ContentTarget,
    ContentType,
    ContentVersion,
    ContentVisibility,
    Favorite,
    Genre,
    Like,
    ModerationStatus,
)
from api.db.models.legal import LegalDocument
from api.db.models.media import Asset, AssetKind, AssetStatus
from api.db.models.moderation import (
    AdminActionLog,
    Appeal,
    AppealStatus,
    AppealTargetKind,
    AppealVerdict,
    ModerationAction,
    ModerationActionType,
    Notification,
    Report,
    ReportReasonCategory,
    ReportStatus,
)
from api.db.models.notice import Notice
from api.db.models.story import (
    Ending,
    EndingRule,
    EndingRuleGroup,
    EndingRuleOperator,
    KeywordNote,
    LogicalOp,
    Shortcut,
    StartingSetup,
    StatDef,
    StoryPromptTemplate,
    StoryVersionDetail,
)

__all__ = [
    "AdminActionLog",
    "AdminUser",
    "Appeal",
    "AppealStatus",
    "AppealTargetKind",
    "AppealVerdict",
    "Asset",
    "AssetKind",
    "AssetStatus",
    "CharacterImageExposure",
    "CharacterVersionDetail",
    "ChatMessage",
    "ChatMessageRole",
    "ChatRoom",
    "ChatRoomStat",
    "Content",
    "ContentTarget",
    "ContentType",
    "ContentVersion",
    "ContentVisibility",
    "Ending",
    "EndingRule",
    "EndingRuleGroup",
    "EndingRuleOperator",
    "Favorite",
    "Genre",
    "GuardianConsent",
    "KeywordNote",
    "LegalDocument",
    "Like",
    "LogicalOp",
    "ModerationAction",
    "ModerationActionType",
    "ModerationStatus",
    "Notice",
    "Notification",
    "Report",
    "ReportReasonCategory",
    "ReportStatus",
    "Shortcut",
    "SituationalImage",
    "StartingSetup",
    "StatDef",
    "StoryEndingUnlock",
    "StoryPromptTemplate",
    "StoryVersionDetail",
    "User",
]
