"""favorites likes reports moderation actions notifications appeals

Revision ID: 0116587e4a53
Revises: b8e8af497520
Create Date: 2026-07-07 22:08:17.783995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0116587e4a53'
down_revision: Union[str, Sequence[str], None] = 'b8e8af497520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appeals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('target_kind', sa.Enum('PUBLISH_REJECTION', 'MODERATION_ACTION', name='appeal_target_kind'), nullable=False),
    sa.Column('target_id', sa.Uuid(), nullable=False),
    sa.Column('reason_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RESOLVED', name='appeal_status'), nullable=False),
    sa.Column('verdict', sa.Enum('ACCEPTED', 'REJECTED', name='appeal_verdict'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'content_id')
    )
    op.create_table('likes',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'content_id')
    )
    op.create_table('moderation_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Enum('RESTRICT', 'LIFT_RESTRICTION', 'DELETE', 'REJECT', name='moderation_action_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reporter_user_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('reason_category', sa.Enum('ADULT', 'COPYRIGHT', 'HATE', 'SPAM', 'OTHER', name='report_reason_category'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RESOLVED', 'REJECTED', name='report_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_by_admin_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Text(), server_default='moderation-action', nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('action_id', sa.Uuid(), nullable=False),
    sa.Column('reason_category', sa.Text(), nullable=False),
    sa.Column('admin_comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('read', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['moderation_actions.id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('reports')
    op.drop_table('moderation_actions')
    op.drop_table('likes')
    op.drop_table('favorites')
    op.drop_table('appeals')
    # ### end Alembic commands ###
    sa.Enum(name='report_reason_category').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='report_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='moderation_action_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='appeal_target_kind').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='appeal_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='appeal_verdict').drop(op.get_bind(), checkfirst=True)
