"""users suspended_at, notifications nullable, admin action logs

Revision ID: 0741a91285ed
Revises: 63ede9a03614
Create Date: 2026-09-06 14:49:28.905116

`admin_action_logs`와 기존 `moderation_actions`(0116587e4a53)의 관계: 콘텐츠 조치는
두 테이블 모두에 기록되며, 이건 중복이 아니라 계층이다. `moderation_actions`는 콘텐츠
조치의 실체 레코드이자 `notifications.action_id`의 FK 대상이라 없앨 수 없다(그 테이블
자체가 유저 대상 조치를 담지 못하는 이유이기도 하다 — `content_id`가 NOT NULL이라
콘텐츠 없는 조치를 표현할 수 없다). `admin_action_logs`는 그 위에 얹는 감사 로그로,
콘텐츠 조치·유저 제재(경고/정지/해제)·채팅 열람을 `action_type`(TEXT, 늘어날 값이라
Postgres enum을 만들지 않았다) 하나로 한데 담는다.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0741a91285ed'
down_revision: Union[str, Sequence[str], None] = '63ede9a03614'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_action_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('admin_id', sa.Uuid(), nullable=False),
    sa.Column('action_type', sa.Text(), nullable=False),
    sa.Column('target_user_id', sa.Uuid(), nullable=True),
    sa.Column('target_content_id', sa.Uuid(), nullable=True),
    sa.Column('target_chat_room_id', sa.Uuid(), nullable=True),
    sa.Column('reason_category', sa.Text(), nullable=True),
    sa.Column('reason_text', sa.Text(), server_default='', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['target_chat_room_id'], ['chat_rooms.id'], ),
    sa.ForeignKeyConstraint(['target_content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_admin_action_logs_created_at', 'admin_action_logs', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_admin_action_logs_target_content_id', 'admin_action_logs', ['target_content_id'], unique=False)
    op.create_index('ix_admin_action_logs_target_user_id', 'admin_action_logs', ['target_user_id'], unique=False)
    op.alter_column('notifications', 'content_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('notifications', 'action_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('users', sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'suspended_at')
    # content_id/action_id가 null인 행이 남아 있으면 이 두 ALTER는 실패한다 — 이 저장소의
    # 다른 downgrade들(예: 7705a5f72c7e)과 같은 수준으로, 방어 코드를 넣지 않는다.
    op.alter_column('notifications', 'action_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('notifications', 'content_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index('ix_admin_action_logs_target_user_id', table_name='admin_action_logs')
    op.drop_index('ix_admin_action_logs_target_content_id', table_name='admin_action_logs')
    op.drop_index('ix_admin_action_logs_created_at', table_name='admin_action_logs')
    op.drop_table('admin_action_logs')
    # ### end Alembic commands ###
