"""beta prep discarded responses and chat message reports

Revision ID: 0ffeb45ff1f4
Revises: bd29dd69bc0f
Create Date: 2026-10-01 22:43:51.847829

추가만 하는 리비전이다(기존 행·컬럼을 바꾸지 않는다). 두 새 테이블의 방·메시지 참조는
`ON DELETE SET NULL`이라 방 삭제·탈퇴·재생성·메시지 삭제가 이 테이블을 몰라도 그대로 지나가고
행은 남는다. 신고 상태는 작품·댓글 신고가 이미 쓰는 `report_status` 타입을 재사용하므로
여기에서 만들지도(`create_type=False`) 지우지도 않는다 — downgrade에서 지우면 그 타입을 쓰는
다른 두 테이블 때문에 실패한다.
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '0ffeb45ff1f4'
down_revision: str | Sequence[str] | None = 'bd29dd69bc0f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discarded_responses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('chat_room_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('discarded_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('discarded_count >= 1', name='ck_discarded_responses_count_positive'),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_discarded_responses_chat_room_id', 'discarded_responses', ['chat_room_id'], unique=False)
    op.create_table('chat_message_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reporter_user_id', sa.Uuid(), nullable=False),
    sa.Column('chat_room_id', sa.Uuid(), nullable=True),
    sa.Column('chat_message_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'RESOLVED', 'REJECTED', name='report_status', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_by_admin_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_response', sa.Text(), nullable=True),
    sa.Column('evidence_user_message', sa.Text(), nullable=True),
    sa.Column('evidence_expires_at', sa.DateTime(timezone=True), server_default=sa.text("now() + interval '90 days'"), nullable=False),
    sa.Column('evidence_purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['chat_message_id'], ['chat_messages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chat_message_id', 'reporter_user_id', name='ux_chat_message_reports_message_reporter')
    )
    op.create_index('ix_chat_message_reports_evidence_expires', 'chat_message_reports', ['evidence_expires_at'], unique=False)
    op.create_index('ix_chat_message_reports_status_created', 'chat_message_reports', ['status', 'created_at', 'id'], unique=False)
    op.add_column('users', sa.Column('beta_joined_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'beta_joined_at')
    op.drop_index('ix_chat_message_reports_status_created', table_name='chat_message_reports')
    op.drop_index('ix_chat_message_reports_evidence_expires', table_name='chat_message_reports')
    op.drop_table('chat_message_reports')
    op.drop_index('ix_discarded_responses_chat_room_id', table_name='discarded_responses')
    op.drop_table('discarded_responses')
    # ### end Alembic commands ###
