"""create situation notes

Revision ID: 470a2fc86186
Revises: afee8eec9671
Create Date: 2026-10-03 21:28:38.578149

시작설정마다 둘 수 있는 상황 노트 테이블을 만든다. 노트의 스탯 조건은 엔딩 규칙과 같은 모양의 JSON 목록 한 칸에 둔다.

이 테이블은 `starting_setups` 를 물리 FK 로 가리킨다. 상황 노트가 든 초안이 있는 채로 API 를 이 테이블을 모르는 이전
이미지로 되돌리면, 그 코드의 시작설정 삭제(저장 중 시작설정 제거·초안 삭제·편집 취소)가 FK 위반으로 실패하고 발행 복제는
노트를 말없이 빠뜨린다. 되돌리기 전에 노트 행을 지우거나 이 리비전까지 함께 내린다.
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '470a2fc86186'
down_revision: str | Sequence[str] | None = 'afee8eec9671'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('situation_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('starting_setup_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), server_default='', nullable=False),
    sa.Column('info_text', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('condition_rules', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.ForeignKeyConstraint(['starting_setup_id'], ['starting_setups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('situation_notes')
    # ### end Alembic commands ###
