"""image generation requests

Revision ID: 4e6d562bf8da
Revises: e00c32bf159a
Create Date: 2026-09-16 19:05:21.733216

지금 이미지 생성 요청(프롬프트·모델·비율·차단
사유)은 아무 데도 남지 않는다 — 성공한 이미지는 `assets` 행이 되지만 왜·무엇으로
만들었는지는 호출 직후 휘발된다. `assets`에 컬럼을 붙이지 않고 별도 테이블로 두는
이유 둘: ① `requested_count`가 2면 같은 프롬프트가 두 asset 행에 중복된다, ②
이미지가 안 나온 요청(차단·실패)은 asset 행 자체가 없어 기록할 자리가 없다.

`status`는 `assets.style`과 같은 이유로 native enum이 아니라 `Text`다 — 값이
늘 때 마이그레이션 없이 넓히기 위해서다.

`assets.request_id`는 nullable이다 — 이 기능 이전에 생성된 자산은 요청 행이 없다.

이 리비전은 스키마만이다. 요청 행을 쓰는 라우터·비즈니스 로직은 별도 변경에서 붙는다.

- **`op.create_foreign_key`에 autogenerate가 이름을 `None`으로 냈다** — 그대로 두면
  downgrade의 `op.drop_constraint(None, ...)`가 실제 제약 이름을 모른 채 호출돼
  실패한다. `aceda536013c`/`bdb8e2ebcf5c` 선례를 따라 `fk_assets_request_id`로
  손으로 이름을 붙였다.
"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e6d562bf8da'
down_revision: str | Sequence[str] | None = 'e00c32bf159a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_generation_requests',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('style', sa.Text(), nullable=False),
    sa.Column('aspect_ratio', sa.Text(), nullable=False),
    sa.Column('model', sa.Text(), nullable=False),
    sa.Column('requested_count', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('completed_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('blocked_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('input_error_count', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('input_error', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_image_generation_requests_created_at', 'image_generation_requests', [sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_image_generation_requests_owner_user_id_created_at', 'image_generation_requests', ['owner_user_id', sa.literal_column('created_at DESC')], unique=False)
    op.add_column('assets', sa.Column('request_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_assets_request_id', 'assets', 'image_generation_requests', ['request_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_assets_request_id', 'assets', type_='foreignkey')
    op.drop_column('assets', 'request_id')
    op.drop_index('ix_image_generation_requests_owner_user_id_created_at', table_name='image_generation_requests')
    op.drop_index('ix_image_generation_requests_created_at', table_name='image_generation_requests')
    op.drop_table('image_generation_requests')
    # ### end Alembic commands ###
