"""chat_messages image_id

Revision ID: 5441c593b7be
Revises: d7d578597b6a
Create Date: 2026-09-18 15:07:25.937655

situational-image-goal-prompt.md SI-1. `chat_messages`에 상황이미지 매칭 결과를
남기는 nullable 컬럼을 하나 추가한다. 과거 행은 이미지가 없었고 백필 대상이
0건이라 지금이 NULL로 둘 수 있는 유일한 시점이다.

FK 없음: 값은 물리 PK가 아니라 상황이미지의 entity_id이고, entity_id는 버전마다
행이 복제돼 유니크가 아니라 FK를 걸 수 없다(situational-image-goal-prompt.md
SI-2). 인덱스도 없음 — 같은 테이블의 형제 컬럼(`ChatRoom.starting_setup_entity_id`
등)과 같은 다형 참조 관례.
"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5441c593b7be'
down_revision: str | Sequence[str] | None = 'd7d578597b6a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('image_id', sa.Uuid(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'image_id')
    # ### end Alembic commands ###
