"""legal documents, users terms/privacy version

Revision ID: 5bef71fc8f50
Revises: 0741a91285ed
Create Date: 2026-09-06 18:18:37.710623

techspec.md §1-4. `kind`/`status`는 native Postgres enum이 아니라 Text로 간다 — 값이
늘어날 여지가 있고(신고·조치 사유 등 다른 목적의 카테고리 확장과 별개로, 약관 종류나
상태 값이 추가될 수 있다), `notifications.type`·`admin_action_logs.action_type`이
이미 이 선례다.

이 저장소 최초의 부분 유니크 인덱스 2개:
- `UNIQUE (kind) WHERE status = 'draft'` — kind별 초안은 최대 1개
- `UNIQUE (kind, version) WHERE status = 'published'` — 같은 (kind, version) 재게시 방지
`op.create_table`이 만드는 PK 인덱스와 달리 이 둘은 `create_index(unique=True,
postgresql_where=...)`로 별도 생성해야 한다. `downgrade()`의 `drop_table`이 테이블에
딸린 모든 인덱스(부분 인덱스 포함)를 함께 지우므로 별도의 `drop_index` 호출은 불필요
하다 — 하지만 순서상 명시적으로 먼저 지워 그 사실을 드러낸다.

공개 조회(kind별 published 중 최신)에 쓸 추가 인덱스는 만들지 않는다 — 문서 종류
2개·문서당 버전 몇 개 규모에서 순차 스캔이면 충분하고, 이 저장소는 이 규모의 테이블에
조회 전용 인덱스를 미리 얹지 않는 관례를 이미 갖고 있다(`chat_messages` 등).
"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bef71fc8f50'
down_revision: str | Sequence[str] | None = '0741a91285ed'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legal_documents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('version', sa.Text(), nullable=True),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('requires_reconsent', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(
        'ix_legal_documents_kind_draft', 'legal_documents', ['kind'],
        unique=True, postgresql_where=sa.text("status = 'draft'"),
    )
    op.create_index(
        'ix_legal_documents_kind_version_published', 'legal_documents', ['kind', 'version'],
        unique=True, postgresql_where=sa.text("status = 'published'"),
    )
    op.add_column('users', sa.Column('terms_version', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('privacy_version', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'privacy_version')
    op.drop_column('users', 'terms_version')
    # 부분 인덱스 둘은 아래 drop_table이 테이블과 함께 지운다 — 명시적으로 먼저 지워
    # 그 사실을 드러낸다.
    op.drop_index('ix_legal_documents_kind_version_published', table_name='legal_documents')
    op.drop_index('ix_legal_documents_kind_draft', table_name='legal_documents')
    op.drop_table('legal_documents')
    # ### end Alembic commands ###
