"""stat_defs per_turn_delta

Revision ID: 5c1d89616a39
Revises: 7705a5f72c7e
Create Date: 2026-08-07 02:53:47.011416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c1d89616a39'
down_revision: Union[str, Sequence[str], None] = '7705a5f72c7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_defs', sa.Column('per_turn_delta', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stat_defs', 'per_turn_delta')
    # ### end Alembic commands ###
