"""create notices

Revision ID: 6040220ae77b
Revises: c49014ae5b62
Create Date: 2026-09-07 23:11:03.033981

goal-prompt.md §3-1, techspec.md §3-1·§3-3(리비전 1/3). `notices`는 제목 + 마크다운
본문 + 게시/숨김 토글의 단순 CRUD다(goal-prompt D-7) — `legal_documents`처럼 초안/버전
이력을 갖는 문서가 아니라 시점별 알림글이라 부분 유니크 인덱스 같은 무결성 장치는
필요 없다.

부분 인덱스 `ix_notices_published_at (published_at DESC) WHERE published`는 목록
조회(게시된 공지를 최신순으로)를 위한 것이고, `postgresql_where`가 생성 SQL에 실제로
들어갔는지 확인했다(`sa.text('published IS true')`). `published`를 `published_at IS
NOT NULL`로 대신하지 않는 이유는 모델 docstring(`db/models/notice.py`) 참고 — 숨김 →
재게시 시 원래 게시일이 유지돼야 하기 때문이다.
"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6040220ae77b'
down_revision: str | Sequence[str] | None = 'c49014ae5b62'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notices',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body_markdown', sa.Text(), nullable=False),
    sa.Column('published', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notices_published_at', 'notices', [sa.literal_column('published_at DESC')], unique=False, postgresql_where=sa.text('published IS true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notices_published_at', table_name='notices', postgresql_where=sa.text('published IS true'))
    op.drop_table('notices')
    # ### end Alembic commands ###
