"""contents has_unpublished_changes

Revision ID: 63ede9a03614
Revises: 5c1d89616a39
Create Date: 2026-08-27 15:16:14.164458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ede9a03614'
down_revision: Union[str, Sequence[str], None] = '5c1d89616a39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOT NULL + server_default 라서 기존 행은 전부 false 로 채워진다 — 그게 의도한 백필이다.
    # 지금 문제가 "편집분이 없는데 빨갛다"이고, 실제 편집분이 있는 콘텐츠는 다음 자동저장에서
    # 곧바로 true 가 된다.
    op.add_column('contents', sa.Column('has_unpublished_changes', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'has_unpublished_changes')
    # ### end Alembic commands ###
