"""novels

Revision ID: 668c7ae16cc0
Revises: 7d7e872c9dc4
Create Date: 2026-10-05 19:32:09.833056

소설화 테이블 넷(소설·장·장 개정·작업). 새 테이블만 만들고 기존 테이블은 건드리지 않는다. 기존 테이블 쪽에서
이 테이블들을 가리키는 FK 가 없어, 되돌리기는 테이블을 지우는 것으로 끝난다(만든 소설은 사라진다).

CHECK 제약은 `alembic check` 가 비교하지 않는다 — 모델의 Literal 을 바꾸면 여기에 맞춘 새 리비전을 손으로 쓴다.

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '668c7ae16cc0'
down_revision: str | Sequence[str] | None = '7d7e872c9dc4'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('novels',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('chat_room_id', sa.Uuid(), nullable=True),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('content_type', sa.Text(), nullable=False),
    sa.Column('content_title', sa.Text(), nullable=False),
    sa.Column('character_name', sa.Text(), nullable=True),
    sa.Column('setting_notes', sa.Text(), server_default='', nullable=False),
    sa.Column('protagonist_name', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_rooms.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_novels_user_id_updated_at', 'novels', ['user_id', sa.literal_column('updated_at DESC')], unique=False)
    op.create_index('ux_novels_chat_room_id', 'novels', ['chat_room_id'], unique=True)
    op.create_table('novel_chapters',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('novel_id', sa.Uuid(), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=False),
    sa.Column('start_message_id', sa.Uuid(), nullable=False),
    sa.Column('start_message_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_message_id', sa.Uuid(), nullable=False),
    sa.Column('end_message_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assistant_message_count', sa.Integer(), nullable=False),
    sa.Column('source_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('assistant_message_count >= 1', name='ck_novel_chapters_assistant_message_count_positive'),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_novel_chapters_novel_id_ordinal', 'novel_chapters', ['novel_id', 'ordinal'], unique=True)
    op.create_table('novel_chapter_revisions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chapter_id', sa.Uuid(), nullable=False),
    sa.Column('revision_no', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('reverted_from_revision_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('generate', 'regenerate', 'manual_edit', 'ai_edit', 'revert')", name='ck_novel_chapter_revisions_source'),
    sa.ForeignKeyConstraint(['chapter_id'], ['novel_chapters.id'], ),
    sa.ForeignKeyConstraint(['reverted_from_revision_id'], ['novel_chapter_revisions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_novel_chapter_revisions_chapter_id_revision_no', 'novel_chapter_revisions', ['chapter_id', 'revision_no'], unique=True)
    op.create_table('novel_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('novel_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('chapter_id', sa.Uuid(), nullable=True),
    sa.Column('base_revision_id', sa.Uuid(), nullable=True),
    sa.Column('start_message_id', sa.Uuid(), nullable=True),
    sa.Column('start_message_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_message_id', sa.Uuid(), nullable=True),
    sa.Column('end_message_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paragraph_start', sa.Integer(), nullable=True),
    sa.Column('paragraph_end', sa.Integer(), nullable=True),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('result_text', sa.Text(), nullable=True),
    sa.Column('charged_amount', sa.Integer(), nullable=False),
    sa.Column('refunded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_code', sa.Text(), nullable=True),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("failure_code IS NULL OR failure_code IN ('llm_error', 'timeout', 'truncated', 'refused', 'blocked', 'empty', 'source_changed', 'expired', 'internal')", name='ck_novel_jobs_failure_code'),
    sa.CheckConstraint("kind IN ('chapter_generate', 'chapter_regenerate', 'ai_edit')", name='ck_novel_jobs_kind'),
    sa.CheckConstraint("refunded_at IS NULL OR status = 'failed'", name='ck_novel_jobs_refund_only_when_failed'),
    sa.CheckConstraint("status IN ('queued', 'running', 'succeeded', 'failed')", name='ck_novel_jobs_status'),
    sa.CheckConstraint('charged_amount >= 0', name='ck_novel_jobs_charged_amount_non_negative'),
    sa.ForeignKeyConstraint(['base_revision_id'], ['novel_chapter_revisions.id'], ),
    sa.ForeignKeyConstraint(['chapter_id'], ['novel_chapters.id'], ),
    sa.ForeignKeyConstraint(['novel_id'], ['novels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_novel_jobs_novel_id_start_message_id_created_at', 'novel_jobs', ['novel_id', 'start_message_id', 'created_at'], unique=False)
    op.create_index('ix_novel_jobs_user_id_created_at', 'novel_jobs', ['user_id', 'created_at'], unique=False)
    op.create_index('ux_novel_jobs_novel_id_active', 'novel_jobs', ['novel_id'], unique=True, postgresql_where=sa.text("status IN ('queued', 'running')"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_novel_jobs_novel_id_active', table_name='novel_jobs', postgresql_where=sa.text("status IN ('queued', 'running')"))
    op.drop_index('ix_novel_jobs_user_id_created_at', table_name='novel_jobs')
    op.drop_index('ix_novel_jobs_novel_id_start_message_id_created_at', table_name='novel_jobs')
    op.drop_table('novel_jobs')
    op.drop_index('ux_novel_chapter_revisions_chapter_id_revision_no', table_name='novel_chapter_revisions')
    op.drop_table('novel_chapter_revisions')
    op.drop_index('ux_novel_chapters_novel_id_ordinal', table_name='novel_chapters')
    op.drop_table('novel_chapters')
    op.drop_index('ux_novels_chat_room_id', table_name='novels')
    op.drop_index('ix_novels_user_id_updated_at', table_name='novels')
    op.drop_table('novels')
    # ### end Alembic commands ###
