"""contents rating

Revision ID: 7d0a4e0b08cf
Revises: 80f5dda86e33
Create Date: 2026-10-05 11:53:24.153350

작품 헤더에 등급 `contents.rating` 을 더하고 전연령(`'all'`)만 허용하는 CHECK 로 잠근다. 성인 등급으로 표시하는
순간 법적 의무가 생기는데 그 의무를 지킬 수단이 아직 없어서다(근거는 `CONTENT_POLICY.md` 의 "이 문서의 위치" 절).
기존 행은 상수 기본값이 채우므로 백필하지 않는다. autogenerate 가 CHECK 를 다루지 않아 손으로 추가했다.
"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d0a4e0b08cf'
down_revision: str | Sequence[str] | None = '80f5dda86e33'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('rating', sa.Text(), server_default='all', nullable=False))
    # ### end Alembic commands ###
    op.create_check_constraint('ck_contents_rating_all_only', 'contents', "rating = 'all'")


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('ck_contents_rating_all_only', 'contents', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'rating')
    # ### end Alembic commands ###
