"""clover

Revision ID: 7d7106509dc9
Revises: 5441c593b7be
Create Date: 2026-09-19 01:01:48.566941

클로버(재화)의 저장은 불변 원장 `clover_ledger` 한 테이블과
`users`의 컬럼 세 개다. 잔액을 원장의 `SUM()`으로 파생시키지 않고 `users.clover_balance`에
두는 이유는 성능이 아니라 **불변식의 소재지**다 — 판정은 이 컬럼의 조건부 UPDATE
(`WHERE clover_balance >= :amount` + `RETURNING`)로 하고 원장은 같은 트랜잭션에 얹는
기록이다. 순서를 뒤집어 원장 SUM으로 판정하면 동시 요청 둘이 서로의 미커밋 INSERT를
못 봐서 이중 지불이 난다.

`kind`는 `assets.style`·`image_generation_requests.status`와 같은 이유로 native
enum이 아니라 `Text`다 — 값이 늘 때 마이그레이션 없이 넓히기 위해서다.

`idempotency_key`는 nullable + unique다. 이 리비전 시점에 채우는 것은 어드민 지급/회수뿐이었고
나머지는 NULL인데, Postgres는 NULL을 중복으로 치지 않으므로
평범한 unique 인덱스가 "값이 있는 것만 유일"이 된다.

`clover_balance`는 NOT NULL + `server_default 0`이라 기존 행이 전부 0으로 채워진다 —
그게 의도한 백필이고(잔액 없음이 기본이다) 별도 UPDATE가 필요 없다
(`d7d578597b6a`가 같은 문장을 쓴 선례).

- **`ck_users_clover_balance_non_negative`는 autogenerate가 만들지 않았다** — alembic
  1.18.5의 autogenerate/compare에는 CHECK 제약 비교자가 없어(`CheckConstraint`를 아예
  다루지 않는다) 손으로 추가했다. 같은 이유로 **`alembic check`는 이 제약을 검증하지
  못하므로** 검증은 `pytest.raises(IntegrityError)` 행위 테스트가 유일하다
  (`db/models/story.py`의 `EndingRule` docstring이 같은 함정을 적어 뒀다).
- FK 이름 `fk_clover_ledger_user_id`를 손으로 붙였다. 이 FK는 `create_table` 안의
  인라인이고 downgrade가 `op.drop_table` 하나뿐이라 **이름을 부를 일이 없다** —
  `4e6d562bf8da`의 `fk_assets_request_id`(별도 `create_foreign_key`라 downgrade가 이름을
  부른다)와 달리 downgrade 때문이 아니라 **이름 규약 일관성과 제약 조회 가독성**을 위해서다.

이 리비전은 스키마만이다. 원장을 쓰는 서비스·게이트·라우터는 별도 변경에서 붙는다.

"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d7106509dc9'
down_revision: str | Sequence[str] | None = '5441c593b7be'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clover_ledger',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('balance_after', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_clover_ledger_user_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clover_ledger_user_id_created_at', 'clover_ledger', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ux_clover_ledger_idempotency_key', 'clover_ledger', ['idempotency_key'], unique=True)
    op.add_column('users', sa.Column('clover_balance', sa.Integer(), server_default=sa.text('0'), nullable=False))
    op.add_column('users', sa.Column('clover_attendance_granted_on', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('clover_spend_confirmed_on', sa.Date(), nullable=True))
    # autogenerate가 CHECK 제약을 다루지 않아 손으로 추가한다(위 docstring).
    op.create_check_constraint('ck_users_clover_balance_non_negative', 'users', 'clover_balance >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_users_clover_balance_non_negative', 'users', type_='check')
    op.drop_column('users', 'clover_spend_confirmed_on')
    op.drop_column('users', 'clover_attendance_granted_on')
    op.drop_column('users', 'clover_balance')
    op.drop_index('ux_clover_ledger_idempotency_key', table_name='clover_ledger')
    op.drop_index('ix_clover_ledger_user_id_created_at', table_name='clover_ledger')
    op.drop_table('clover_ledger')
    # ### end Alembic commands ###
