"""user_feature_grants

Revision ID: 7d7e872c9dc4
Revises: 00ce650038ba
Create Date: 2026-10-05 18:55:34.789462

계정별 기능 허용 테이블. 행이 있으면 그 계정에 그 기능을 허용한 것이고 회수는 행 DELETE 다. 새 테이블만
만들고 기존 행은 건드리지 않아 되돌리기는 테이블을 지우는 것으로 끝난다(허용 기록은 사라지고 감사 로그는 남는다).

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d7e872c9dc4'
down_revision: str | Sequence[str] | None = '00ce650038ba'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_feature_grants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('feature', sa.Text(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('granted_by', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_user_feature_grants_user_id_feature', 'user_feature_grants', ['user_id', 'feature'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_user_feature_grants_user_id_feature', table_name='user_feature_grants')
    op.drop_table('user_feature_grants')
    # ### end Alembic commands ###
