"""version details default user name

Revision ID: 85df98c44368
Revises: 181fdfb55564
Create Date: 2026-10-04 14:33:49.818226

스토리·캐릭터 버전에 작품 기본 이름 칸을 더한다. 대화 프로필이 없는 사용자를 작가 글의 `{{user}}` 자리에서 부를
이름이고, 기존 행은 빈 값(= 대체어 "당신")으로 시작한다. `server_default` 를 두는 것은 이 컬럼을 모르는 이전 API
이미지로 되돌려도 그 코드의 INSERT(새 초안·발행 복제·시드)가 NOT NULL 위반이 되지 않게 하려는 것이다.
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85df98c44368'
down_revision: str | Sequence[str] | None = '181fdfb55564'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_version_details', sa.Column('default_user_name', sa.Text(), server_default='', nullable=False))
    op.add_column('story_version_details', sa.Column('default_user_name', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story_version_details', 'default_user_name')
    op.drop_column('character_version_details', 'default_user_name')
    # ### end Alembic commands ###
