"""story details, starting setups, stat defs schema

Revision ID: 8b0985a28d4e
Revises: d132c79267d1
Create Date: 2026-07-07 21:49:15.345191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8b0985a28d4e'
down_revision: Union[str, Sequence[str], None] = 'd132c79267d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('starting_setups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('content_version_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('prologue', sa.Text(), nullable=False),
    sa.Column('opening_message', sa.Text(), nullable=True),
    sa.Column('playguide', sa.Text(), nullable=True),
    sa.Column('suggested_replies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['content_version_id'], ['content_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('story_version_details',
    sa.Column('content_version_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('one_liner', sa.Text(), nullable=False),
    sa.Column('thumbnail_asset_id', sa.Uuid(), nullable=False),
    sa.Column('prompt_template', sa.Enum('BASIC', 'EMOTIONAL', 'SIMULATION', 'CUSTOM', name='story_prompt_template'), nullable=False),
    sa.Column('setting_text', sa.Text(), nullable=True),
    sa.Column('development_example', sa.Text(), nullable=True),
    sa.Column('custom_prompt', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['content_version_id'], ['content_versions.id'], ),
    sa.ForeignKeyConstraint(['thumbnail_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('content_version_id')
    )
    op.create_table('stat_defs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('starting_setup_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('icon', sa.Text(), nullable=False),
    sa.Column('color', sa.Text(), nullable=False),
    sa.Column('min_value', sa.Integer(), nullable=False),
    sa.Column('max_value', sa.Integer(), nullable=False),
    sa.Column('initial_value', sa.Integer(), nullable=False),
    sa.Column('unit', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['starting_setup_id'], ['starting_setups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stat_defs')
    op.drop_table('story_version_details')
    op.drop_table('starting_setups')
    # bare op.drop_table above doesn't carry column type info, so it never fires
    # the ENUM type's own after_drop DDL event — drop it explicitly here.
    sa.Enum(name='story_prompt_template').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
