"""content common schema

Revision ID: 91a008760f4a
Revises: aceda536013c
Create Date: 2026-07-07 21:40:23.001990

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91a008760f4a'
down_revision: Union[str, Sequence[str], None] = 'aceda536013c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genres',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('CHARACTER', 'STORY', name='content_type'), nullable=False),
    sa.Column('creator_user_id', sa.Uuid(), nullable=False),
    sa.Column('genre_id', sa.Uuid(), nullable=False),
    sa.Column('target', sa.Enum('FEMALE', 'MALE', 'ALL', name='content_target'), nullable=False),
    sa.Column('hashtags', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('visibility', sa.Enum('PUBLIC', 'LINK', 'PRIVATE', name='content_visibility'), nullable=False),
    sa.Column('moderation_status', sa.Enum('NORMAL', 'RESTRICTED', 'DELETED', name='moderation_status'), nullable=False),
    sa.Column('current_published_version_id', sa.Uuid(), nullable=True),
    sa.Column('view_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('like_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('chat_count', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genres.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('content_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('detail_description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # contents.current_published_version_id -> content_versions.id is added via a
    # separate ALTER TABLE (not inline on create_table) because content_versions.content_id
    # -> contents.id creates a table-creation cycle; op.create_table does not honor
    # use_alter, so the FK must be split out manually here (same pattern as
    # users.profile_image_asset_id -> assets.id).
    op.create_foreign_key(
        'fk_contents_current_published_version_id',
        'contents', 'content_versions',
        ['current_published_version_id'], ['id'],
    )
    op.execute(
        "INSERT INTO genres (id, name, sort_order) VALUES "
        "('b8a1e6b0-1c1a-4b8a-9b0a-000000000001', '로맨스', 1), "
        "('b8a1e6b0-1c1a-4b8a-9b0a-000000000002', '판타지', 2), "
        "('b8a1e6b0-1c1a-4b8a-9b0a-000000000003', '미스터리·스릴러', 3), "
        "('b8a1e6b0-1c1a-4b8a-9b0a-000000000004', 'SF', 4), "
        "('b8a1e6b0-1c1a-4b8a-9b0a-000000000005', '일상', 5), "
        "('b8a1e6b0-1c1a-4b8a-9b0a-000000000006', '학원', 6), "
        "('b8a1e6b0-1c1a-4b8a-9b0a-000000000007', '공포', 7), "
        "('b8a1e6b0-1c1a-4b8a-9b0a-000000000008', '개그·코미디', 8), "
        "('b8a1e6b0-1c1a-4b8a-9b0a-000000000009', '무협·액션', 9), "
        "('b8a1e6b0-1c1a-4b8a-9b0a-00000000000a', '힐링', 10)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_contents_current_published_version_id', 'contents', type_='foreignkey')
    op.drop_table('content_versions')
    op.drop_table('contents')
    op.drop_table('genres')
    # bare op.drop_table above doesn't carry column type info, so it never fires
    # each ENUM type's own after_drop DDL event — drop them explicitly here.
    sa.Enum(name='content_type').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='content_target').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='content_visibility').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='moderation_status').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
