"""character draft nullable columns

Revision ID: a638f002826b
Revises: e64d71eaa642
Create Date: 2026-07-08 18:32:54.542696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a638f002826b'
down_revision: Union[str, Sequence[str], None] = 'e64d71eaa642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('character_version_details', 'thumbnail_asset_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('contents', 'genre_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('contents', 'target',
               existing_type=postgresql.ENUM('FEMALE', 'MALE', 'ALL', name='content_target'),
               nullable=True)
    op.alter_column('situational_images', 'image_asset_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('situational_images', 'blurred_asset_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('situational_images', 'blurred_asset_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('situational_images', 'image_asset_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('contents', 'target',
               existing_type=postgresql.ENUM('FEMALE', 'MALE', 'ALL', name='content_target'),
               nullable=False)
    op.alter_column('contents', 'genre_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('character_version_details', 'thumbnail_asset_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
