"""auth and media schema

Revision ID: aceda536013c
Revises: 
Create Date: 2026-07-07 21:20:51.739987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'aceda536013c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('google_sub', sa.Text(), nullable=True),
    sa.Column('nickname', sa.Text(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('terms_agreed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('privacy_agreed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('profile_image_asset_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_sub')
    )
    op.create_table('assets',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('kind', sa.Enum('ORIGINAL', 'BLURRED', 'THUMBNAIL', name='asset_kind'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # users.profile_image_asset_id -> assets.id is added via a separate ALTER TABLE
    # (not inline on create_table) because assets.owner_user_id -> users.id creates
    # a table-creation cycle; op.create_table does not honor use_alter, so the FK
    # must be split out manually here.
    op.create_foreign_key('fk_users_profile_image_asset_id', 'users', 'assets', ['profile_image_asset_id'], ['id'])
    op.create_table('guardian_consents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('guardian_name', sa.Text(), nullable=False),
    sa.Column('guardian_contact', sa.Text(), nullable=False),
    sa.Column('consent_agreed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('guardian_consents')
    op.drop_constraint('fk_users_profile_image_asset_id', 'users', type_='foreignkey')
    op.drop_table('assets')
    op.drop_table('users')
    op.drop_table('admin_users')
    # bare op.drop_table above doesn't carry column type info, so it never fires
    # the ENUM type's own after_drop DDL event — drop it explicitly here.
    sa.Enum(name='asset_kind').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
