"""content chat participants

Revision ID: ade2c1031e12
Revises: b7db3d8a5201
Create Date: 2026-10-03 22:42:53.904785

`contents.chat_count` 를 "그 작품과 대화를 시작한 사람 수(작가 본인 제외)" 로 세기 위해 (작품, 사용자) 쌍을
기록하는 `content_chat_participants` 를 만들고, 현존 방에서 쌍을 채운 뒤 수를 맞춘다. 지금까지 `chat_count` 를
올리는 코드가 없어 값이 전부 0 이었다.

백필 한계: 방은 하드 삭제되므로(사용자 삭제·탈퇴 파기) 이미 지워진 방의 대화 상대는 되살릴 수 없어 세지 않는다.
작가 본인 방은 넣지 않는다. 테스트 계정의 방도 일반 사용자와 똑같이 센다. 수는 모든 작품에 대해 기록 행 수로
덮어쓴다 — 방이 없는 작품은 0 이 된다.

downgrade 는 표를 지우고 `chat_count` 를 전부 0 으로 되돌린다. 이 리비전 이전에는 `chat_count` 를 올리는 코드가
없었으므로, 배포 전 운영 값이 전부 0 이었다면 이것이 배포 전 상태 그대로다. 그 전제(운영 값이 전부 0)는 배포 전에
운영에서 읽기 전용 조회로 확인해야 한다 — 0 이 아닌 값이 있었다면 downgrade 는 그 값을 되살리지 못한다. 배포
뒤에 쌓인 증가분도 downgrade 로 사라진다.
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ade2c1031e12'
down_revision: str | Sequence[str] | None = 'b7db3d8a5201'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# 현존 방의 서로 다른 (작품, 사용자) 쌍을 넣는다. 작가 본인 방은 뺀다. 기록 시각은 그 쌍의 가장 이른 방 생성 시각이다.
# 테스트가 이 문장을 그대로 실행해 단언한다.
BACKFILL_PARTICIPANTS_SQL = """
INSERT INTO content_chat_participants (content_id, user_id, created_at)
SELECT r.content_id, r.user_id, min(r.created_at)
FROM chat_rooms r
JOIN contents c ON c.id = r.content_id
WHERE r.user_id <> c.creator_user_id
GROUP BY r.content_id, r.user_id
"""

# 모든 작품의 수를 기록 행 수로 맞춘다(방이 없는 작품은 0). 테스트가 이 문장을 그대로 실행해 단언한다.
BACKFILL_CHAT_COUNT_SQL = """
UPDATE contents c
SET chat_count = (SELECT count(*) FROM content_chat_participants p WHERE p.content_id = c.id)
"""


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('content_chat_participants',
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('content_id', 'user_id')
    )
    # ### end Alembic commands ###
    op.execute(BACKFILL_PARTICIPANTS_SQL)
    op.execute(BACKFILL_CHAT_COUNT_SQL)


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("UPDATE contents SET chat_count = 0")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('content_chat_participants')
    # ### end Alembic commands ###
