"""stat_defs change direction and max change per turn

Revision ID: afee8eec9671
Revises: b7db3d8a5201
Create Date: 2026-10-03 21:00:40.265944

판정 LLM 이 정하는 스탯에 "변화 방향"과 "한 턴 최대 폭" 옵션을 더한다. 기존 행은 양방향·제한 없음으로 시작하므로
지금까지와 똑같이 움직인다. 방향에 `server_default` 를 두는 것은 이 컬럼을 모르는 이전 API 이미지로 되돌려도 그 코드의
스탯 INSERT(저장·발행 복제·시드)가 NOT NULL 위반이 되지 않게 하려는 것이다.
"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afee8eec9671'
down_revision: str | Sequence[str] | None = 'b7db3d8a5201'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stat_defs', sa.Column('change_direction', sa.Text(), server_default='both', nullable=False))
    op.add_column('stat_defs', sa.Column('max_change_per_turn', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stat_defs', 'max_change_per_turn')
    op.drop_column('stat_defs', 'change_direction')
    # ### end Alembic commands ###
