"""keyword notes shortcuts endings ending rules schema

Revision ID: b041021bc734
Revises: 8b0985a28d4e
Create Date: 2026-07-07 21:55:38.909403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b041021bc734'
down_revision: Union[str, Sequence[str], None] = '8b0985a28d4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortcuts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('content_version_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['content_version_id'], ['content_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('endings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('starting_setup_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('turn_count_gate', sa.Integer(), nullable=False),
    sa.Column('judgment_prompt', sa.Text(), nullable=False),
    sa.Column('epilogue', sa.Text(), nullable=True),
    sa.Column('hint', sa.Text(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['starting_setup_id'], ['starting_setups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword_notes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('content_version_id', sa.Uuid(), nullable=False),
    sa.Column('starting_setup_id', sa.Uuid(), nullable=True),
    sa.Column('info_text', sa.Text(), nullable=False),
    sa.Column('trigger_keywords', sa.ARRAY(sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['content_version_id'], ['content_versions.id'], ),
    sa.ForeignKeyConstraint(['starting_setup_id'], ['starting_setups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ending_rule_groups',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('ending_id', sa.Uuid(), nullable=False),
    sa.Column('next_op', sa.Enum('AND', 'OR', name='logical_op'), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ending_id'], ['endings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ending_rules',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('ending_id', sa.Uuid(), nullable=True),
    sa.Column('rule_group_id', sa.Uuid(), nullable=True),
    sa.Column('stat_def_entity_id', sa.Uuid(), nullable=False),
    sa.Column('operator', sa.Enum('GTE', 'LTE', 'EQ', 'GT', 'LT', name='ending_rule_operator'), nullable=False),
    sa.Column('threshold', sa.Numeric(), nullable=False),
    sa.Column('next_op', sa.Enum('AND', 'OR', name='logical_op'), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.CheckConstraint('(ending_id IS NOT NULL) <> (rule_group_id IS NOT NULL)', name='ck_ending_rules_exactly_one_parent'),
    sa.ForeignKeyConstraint(['ending_id'], ['endings.id'], ),
    sa.ForeignKeyConstraint(['rule_group_id'], ['ending_rule_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ending_rules')
    op.drop_table('ending_rule_groups')
    op.drop_table('keyword_notes')
    op.drop_table('endings')
    op.drop_table('shortcuts')
    # ### end Alembic commands ###
    # bare op.drop_table above doesn't carry column type info, so it never fires
    # the ENUM types' own after_drop DDL event — drop them explicitly here.
    sa.Enum(name='ending_rule_operator').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='logical_op').drop(op.get_bind(), checkfirst=True)
