"""contents restricted by suspension

Revision ID: b7db3d8a5201
Revises: 859b0fb86629
Create Date: 2026-10-03 02:07:50.892129

작가 계정 정지가 내린 작품을 표시하는 `contents.restricted_by_suspension` 을 더한다. 정지 해제는 이 표식이 선
작품만 정상으로 되돌린다. 지금까지 정지는 어느 작품을 내렸는지 남기지 않았으므로 기존 행은 전부 false 로 시작한다 —
이 리비전 이전에 정지된 사용자의 작품은 해제해도 돌아오지 않는다. 백필은 하지 않는다 — 작성 시점(2026-10-03)
운영 읽기 전용 조회에서 정지 중인 사용자 0명, 제한 작품 0건이었다. 배포 전에 정지가 생기면 그 작품은 관리자가
작품별로 제한을 해제해야 한다.

표식은 제한 상태에서만 설 수 있다는 CHECK 를 함께 건다. autogenerate 가 CHECK 를 다루지 않아 손으로 추가했다.
"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7db3d8a5201'
down_revision: str | Sequence[str] | None = '859b0fb86629'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contents', sa.Column('restricted_by_suspension', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###
    op.create_check_constraint(
        'ck_contents_suspension_flag_only_when_restricted',
        'contents',
        "NOT restricted_by_suspension OR moderation_status = 'RESTRICTED'",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint('ck_contents_suspension_flag_only_when_restricted', 'contents', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contents', 'restricted_by_suspension')
    # ### end Alembic commands ###
