"""chat_rooms_messages_stats_unlocks_exposures

Revision ID: b8e8af497520
Revises: b041021bc734
Create Date: 2026-07-07 22:01:50.067818

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8e8af497520'
down_revision: Union[str, Sequence[str], None] = 'b041021bc734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_ending_unlocks',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('starting_setup_entity_id', sa.Uuid(), nullable=False),
    sa.Column('ending_entity_id', sa.Uuid(), nullable=False),
    sa.Column('first_reached_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'starting_setup_entity_id', 'ending_entity_id')
    )
    op.create_table('character_image_exposures',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('image_entity_id', sa.Uuid(), nullable=False),
    sa.Column('first_exposed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'content_id', 'image_entity_id')
    )
    op.create_table('chat_rooms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('content_version_id', sa.Uuid(), nullable=False),
    sa.Column('starting_setup_entity_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('turn_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('ending_reached', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('ending_entity_id', sa.Uuid(), nullable=True),
    sa.Column('ending_reached_at_turn', sa.Integer(), nullable=True),
    sa.Column('version_auto_upgraded', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['content_version_id'], ['content_versions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('chat_room_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', name='chat_message_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_room_stats',
    sa.Column('chat_room_id', sa.Uuid(), nullable=False),
    sa.Column('stat_entity_id', sa.Uuid(), nullable=False),
    sa.Column('current_value', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['chat_room_id'], ['chat_rooms.id'], ),
    sa.PrimaryKeyConstraint('chat_room_id', 'stat_entity_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_room_stats')
    op.drop_table('chat_messages')
    op.drop_table('chat_rooms')
    op.drop_table('character_image_exposures')
    op.drop_table('story_ending_unlocks')
    # ### end Alembic commands ###
    sa.Enum(name='chat_message_role').drop(op.get_bind(), checkfirst=True)
