"""character detail and situational images schema

Revision ID: d132c79267d1
Revises: 91a008760f4a
Create Date: 2026-07-07 21:45:36.684914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd132c79267d1'
down_revision: Union[str, Sequence[str], None] = '91a008760f4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_version_details',
    sa.Column('content_version_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('one_liner', sa.Text(), nullable=False),
    sa.Column('thumbnail_asset_id', sa.Uuid(), nullable=False),
    sa.Column('intro', sa.Text(), nullable=False),
    sa.Column('example_dialogues', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('character_prompt', sa.Text(), nullable=False),
    sa.Column('playguide', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['content_version_id'], ['content_versions.id'], ),
    sa.ForeignKeyConstraint(['thumbnail_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('content_version_id')
    )
    op.create_table('situational_images',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('content_version_id', sa.Uuid(), nullable=False),
    sa.Column('image_asset_id', sa.Uuid(), nullable=False),
    sa.Column('blurred_asset_id', sa.Uuid(), nullable=False),
    sa.Column('trigger_condition', sa.Text(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blurred_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['content_version_id'], ['content_versions.id'], ),
    sa.ForeignKeyConstraint(['image_asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('situational_images')
    op.drop_table('character_version_details')
    # ### end Alembic commands ###
