"""users rate_limit_exempt

Revision ID: d7d578597b6a
Revises: 4e6d562bf8da
Create Date: 2026-09-18 00:07:52.061155

limit-goal-prompt.md RL-9. 유저별 채팅 상한의 예외 플래그. 상한값 자체는 상수·재배포라
(RL-14/E-6) 이 컬럼은 값이 아니라 "예외인가"만 담는다.

이 리비전은 스키마만이다 — 게이트가 이 값을 읽는 건 S5, 어드민 토글은 S7이다.

"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7d578597b6a'
down_revision: str | Sequence[str] | None = '4e6d562bf8da'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # NOT NULL + server_default false 라서 기존 행은 전부 false 로 채워진다 — 그게 의도한
    # 백필이고(예외는 기본이 아니다) 별도 UPDATE 가 필요 없다.
    op.add_column('users', sa.Column('rate_limit_exempt', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rate_limit_exempt')
    # ### end Alembic commands ###
