"""assets status column

Revision ID: e64d71eaa642
Revises: 0116587e4a53
Create Date: 2026-07-07 22:46:12.519153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e64d71eaa642'
down_revision: Union[str, Sequence[str], None] = '0116587e4a53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Unlike op.create_table, op.add_column does not implicitly CREATE TYPE for a
    # new enum column, so the type must be created explicitly first.
    sa.Enum('PENDING', 'READY', name='asset_status').create(op.get_bind(), checkfirst=True)
    op.add_column('assets', sa.Column('status', sa.Enum('PENDING', 'READY', name='asset_status'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'status')
    # ### end Alembic commands ###
    sa.Enum(name='asset_status').drop(op.get_bind(), checkfirst=True)
