"""work comments mentions reactions and moderation

Revision ID: e6d1de89970a
Revises: 739e7f1039b1
Create Date: 2026-09-30 21:26:45.309159

작품은 기존 테이블이므로 고정 댓글 FK를 댓글 생성 뒤 추가한다. 신고 사유/상태 ENUM은
기존 작품 신고 타입을 재사용하며 여기에서 생성하거나 삭제하지 않는다. 기존 테이블에
추가하는 FK는 downgrade가 실제로 제거할 수 있도록 명시적으로 이름을 부여한다.
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'e6d1de89970a'
down_revision: str | Sequence[str] | None = '739e7f1039b1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment_stickers',
    sa.Column('id', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('alt', sa.Text(), nullable=False),
    sa.Column('image_path', sa.Text(), nullable=False),
    sa.Column('is_selectable', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comment_mutes',
    sa.Column('viewer_user_id', sa.Uuid(), nullable=False),
    sa.Column('target_user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('viewer_user_id <> target_user_id', name='ck_comment_mutes_not_self'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['viewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('viewer_user_id', 'target_user_id')
    )
    op.create_table('comment_notification_preferences',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('new_comment', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('reply', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('mention', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('content_id', sa.Uuid(), nullable=False),
    sa.Column('author_user_id', sa.Uuid(), nullable=False),
    sa.Column('root_comment_id', sa.Uuid(), nullable=True),
    sa.Column('reply_to_comment_id', sa.Uuid(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('sticker_id', sa.Text(), nullable=True),
    sa.Column('is_spoiler', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('inherited_spoiler', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('creator_hidden', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('moderator_hidden', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('request_id', sa.Uuid(), nullable=False),
    sa.Column('request_fingerprint', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('(root_comment_id IS NULL AND reply_to_comment_id IS NULL) OR (root_comment_id IS NOT NULL AND reply_to_comment_id IS NOT NULL)', name='ck_comments_reply_references_together'),
    sa.CheckConstraint('reply_to_comment_id IS NULL OR reply_to_comment_id <> id', name='ck_comments_not_own_reply_target'),
    sa.CheckConstraint('root_comment_id IS NULL OR root_comment_id <> id', name='ck_comments_not_own_root'),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ),
    sa.ForeignKeyConstraint(['reply_to_comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['root_comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['sticker_id'], ['comment_stickers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_user_id', 'request_id', name='ux_comments_author_request')
    )
    op.create_index('ix_comments_author', 'comments', ['author_user_id'], unique=False)
    op.create_index('ix_comments_content_root_created', 'comments', ['content_id', 'root_comment_id', 'created_at', 'id'], unique=False)
    op.create_index('ix_comments_reply_target', 'comments', ['reply_to_comment_id'], unique=False)
    op.create_table('comment_likes',
    sa.Column('comment_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('comment_id', 'user_id')
    )
    op.create_index('ix_comment_likes_user', 'comment_likes', ['user_id'], unique=False)
    op.create_table('comment_mentions',
    sa.Column('comment_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('comment_id', 'user_id')
    )
    op.create_table('comment_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('reporter_user_id', sa.Uuid(), nullable=False),
    sa.Column('comment_id', sa.Uuid(), nullable=False),
    sa.Column('reason_category', postgresql.ENUM('ADULT', 'COPYRIGHT', 'HATE', 'SPAM', 'OTHER', name='report_reason_category', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'RESOLVED', 'REJECTED', name='report_status', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_by_admin_id', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('evidence_body', sa.Text(), nullable=True),
    sa.Column('evidence_sticker_id', sa.Text(), nullable=True),
    sa.Column('evidence_mention_user_ids', sa.ARRAY(sa.Uuid()), server_default=sa.text("'{}'::uuid[]"), nullable=False),
    sa.Column('evidence_expires_at', sa.DateTime(timezone=True), server_default=sa.text("now() + interval '90 days'"), nullable=False),
    sa.Column('evidence_purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['evidence_sticker_id'], ['comment_stickers.id'], ),
    sa.ForeignKeyConstraint(['reporter_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resolved_by_admin_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reporter_user_id', 'comment_id', name='ux_comment_reports_reporter_comment')
    )
    op.create_index('ix_comment_reports_evidence_expires', 'comment_reports', ['evidence_expires_at'], unique=False)
    op.create_index('ix_comment_reports_status_created', 'comment_reports', ['status', 'created_at', 'id'], unique=False)
    op.create_table('comment_moderation_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('comment_id', sa.Uuid(), nullable=False),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.Column('admin_id', sa.Uuid(), nullable=False),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('reason_category', sa.Text(), nullable=True),
    sa.Column('admin_comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ),
    sa.ForeignKeyConstraint(['report_id'], ['comment_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comment_moderation_actions_comment', 'comment_moderation_actions', ['comment_id', 'created_at'], unique=False)
    op.add_column('contents', sa.Column('comments_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('contents', sa.Column('pinned_comment_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_contents_pinned_comment_id', 'contents', 'comments', ['pinned_comment_id'], ['id'], use_alter=True)
    op.add_column('notifications', sa.Column('comment_id', sa.Uuid(), nullable=True))
    op.add_column('notifications', sa.Column('actor_user_id', sa.Uuid(), nullable=True))
    op.add_column('notifications', sa.Column('comment_action_id', sa.Uuid(), nullable=True))
    op.create_index('ix_notifications_user_created', 'notifications', ['user_id', 'created_at', 'id'], unique=False)
    op.create_index('ux_notifications_comment_action_user', 'notifications', ['comment_action_id', 'user_id'], unique=True, postgresql_where=sa.text('comment_action_id IS NOT NULL'))
    op.create_index('ux_notifications_comment_user', 'notifications', ['comment_id', 'user_id'], unique=True, postgresql_where=sa.text('comment_id IS NOT NULL AND comment_action_id IS NULL'))
    op.create_foreign_key('fk_notifications_comment_id', 'notifications', 'comments', ['comment_id'], ['id'])
    op.create_foreign_key('fk_notifications_comment_action_id', 'notifications', 'comment_moderation_actions', ['comment_action_id'], ['id'])
    op.create_foreign_key('fk_notifications_actor_user_id', 'notifications', 'users', ['actor_user_id'], ['id'])
    op.add_column('admin_action_logs', sa.Column('target_comment_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_admin_action_logs_target_comment_id', 'admin_action_logs', 'comments', ['target_comment_id'], ['id'])
    # ### end Alembic commands ###

    # 자산 ID와 경로는 모든 환경에서 동일하다. 실제 이미지는 web에서 제공한다.
    stickers = sa.table(
        'comment_stickers',
        sa.column('id', sa.Text()),
        sa.column('name', sa.Text()),
        sa.column('alt', sa.Text()),
        sa.column('image_path', sa.Text()),
    )
    op.bulk_insert(stickers, [
        {'id': 'ddona-hello', 'name': '인사', 'alt': '손을 흔들며 인사하는 또나', 'image_path': '/comment-stickers/ddona-hello.webp'},
        {'id': 'ddona-thanks', 'name': '감사', 'alt': '두 손을 모아 감사하는 또나', 'image_path': '/comment-stickers/ddona-thanks.webp'},
        {'id': 'ddona-cheer', 'name': '응원', 'alt': '양 주먹을 올려 응원하는 또나', 'image_path': '/comment-stickers/ddona-cheer.webp'},
        {'id': 'ddona-happy', 'name': '기쁨', 'alt': '양팔을 들고 기뻐하는 또나', 'image_path': '/comment-stickers/ddona-happy.webp'},
        {'id': 'ddona-laugh', 'name': '웃음', 'alt': '눈을 감고 배를 잡으며 웃는 또나', 'image_path': '/comment-stickers/ddona-laugh.webp'},
        {'id': 'ddona-moved', 'name': '감동', 'alt': '눈물을 글썽이며 감동한 또나', 'image_path': '/comment-stickers/ddona-moved.webp'},
        {'id': 'ddona-surprised', 'name': '놀람', 'alt': '눈을 크게 뜨고 놀란 또나', 'image_path': '/comment-stickers/ddona-surprised.webp'},
        {'id': 'ddona-sad', 'name': '아쉬움', 'alt': '팔을 늘어뜨리고 아쉬워하는 또나', 'image_path': '/comment-stickers/ddona-sad.webp'},
    ])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_admin_action_logs_target_comment_id', 'admin_action_logs', type_='foreignkey')
    op.drop_column('admin_action_logs', 'target_comment_id')
    op.drop_constraint('fk_notifications_actor_user_id', 'notifications', type_='foreignkey')
    op.drop_constraint('fk_notifications_comment_action_id', 'notifications', type_='foreignkey')
    op.drop_constraint('fk_notifications_comment_id', 'notifications', type_='foreignkey')
    op.drop_index('ux_notifications_comment_user', table_name='notifications', postgresql_where=sa.text('comment_id IS NOT NULL AND comment_action_id IS NULL'))
    op.drop_index('ux_notifications_comment_action_user', table_name='notifications', postgresql_where=sa.text('comment_action_id IS NOT NULL'))
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_column('notifications', 'comment_action_id')
    op.drop_column('notifications', 'actor_user_id')
    op.drop_column('notifications', 'comment_id')
    op.drop_constraint('fk_contents_pinned_comment_id', 'contents', type_='foreignkey')
    op.drop_column('contents', 'pinned_comment_id')
    op.drop_column('contents', 'comments_enabled')
    op.drop_index('ix_comment_moderation_actions_comment', table_name='comment_moderation_actions')
    op.drop_table('comment_moderation_actions')
    op.drop_index('ix_comment_reports_status_created', table_name='comment_reports')
    op.drop_index('ix_comment_reports_evidence_expires', table_name='comment_reports')
    op.drop_table('comment_reports')
    op.drop_table('comment_mentions')
    op.drop_index('ix_comment_likes_user', table_name='comment_likes')
    op.drop_table('comment_likes')
    op.drop_index('ix_comments_reply_target', table_name='comments')
    op.drop_index('ix_comments_content_root_created', table_name='comments')
    op.drop_index('ix_comments_author', table_name='comments')
    op.drop_table('comments')
    op.drop_table('comment_notification_preferences')
    op.drop_table('comment_mutes')
    op.drop_table('comment_stickers')
    # ### end Alembic commands ###
