"""create inquiries

Revision ID: e933fcbb7938
Revises: bdb8e2ebcf5c
Create Date: 2026-09-08 07:51:27.062093

goal-prompt.md §3-2·§6(T-13), techspec.md §3-1·§3-3(리비전 3/3). 문의 접수 + 답변 3컬럼
(D-11 — 별도 `inquiry_replies` 테이블이 아니라 `reply_body`/`replied_by_admin_id`/
`answered_at`)과 `notifications.inquiry_id` FK를 함께 추가한다.

- **`op.create_foreign_key`에 autogenerate가 이름을 `None`으로 냈다** — 그대로 두면
  downgrade의 `op.drop_constraint(None, ...)`가 실제 제약 이름을 모른 채 호출돼 실패한다.
  `bdb8e2ebcf5c`(`fk_notifications_notice_id`) 선례를 따라 `fk_notifications_inquiry_id`로
  손으로 이름을 붙였다.
- **ENUM 2종(`inquiry_category`/`inquiry_status`)은 신규 테이블에 붙어 `CREATE TYPE`이
  자동으로 나가지만, `op.drop_table`은 `DROP TYPE`을 내보내지 않는다** — downgrade 끝에
  `sa.Enum(name=...).drop(op.get_bind(), checkfirst=True)`를 손으로 추가했다
  (`apps/api/CLAUDE.md` §마이그레이션 ENUM 함정 1).
"""
from typing import Union
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e933fcbb7938'
down_revision: str | Sequence[str] | None = 'bdb8e2ebcf5c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquiries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('category', sa.Enum('ACCOUNT', 'BUG', 'CONTENT', 'SUGGESTION', 'OTHER', name='inquiry_category'), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('attachment_asset_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ANSWERED', name='inquiry_status'), nullable=False),
    sa.Column('reply_body', sa.Text(), nullable=True),
    sa.Column('replied_by_admin_id', sa.Uuid(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['attachment_asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['replied_by_admin_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inquiries_status_created_at', 'inquiries', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('ix_inquiries_user_id_created_at', 'inquiries', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.add_column('notifications', sa.Column('inquiry_id', sa.Uuid(), nullable=True))
    op.create_foreign_key('fk_notifications_inquiry_id', 'notifications', 'inquiries', ['inquiry_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_notifications_inquiry_id', 'notifications', type_='foreignkey')
    op.drop_column('notifications', 'inquiry_id')
    op.drop_index('ix_inquiries_user_id_created_at', table_name='inquiries')
    op.drop_index('ix_inquiries_status_created_at', table_name='inquiries')
    op.drop_table('inquiries')
    # ### end Alembic commands ###
    # op.drop_table은 DROP TYPE을 내보내지 않는다 — 손으로 ENUM 2종을 지운다.
    sa.Enum(name='inquiry_status').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='inquiry_category').drop(op.get_bind(), checkfirst=True)
