"""story draft nullable thumbnail

Revision ID: ec416a217f5d
Revises: a638f002826b
Create Date: 2026-07-08 19:07:18.269050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec416a217f5d'
down_revision: Union[str, Sequence[str], None] = 'a638f002826b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('story_version_details', 'thumbnail_asset_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('story_version_details', 'thumbnail_asset_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
